---
apiVersion: v1
kind: Namespace
metadata:
  name: developer-iq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: developer-iq
  name: metrics-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics-app
  replicas: 4
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metrics-app
    spec:
      containers:
      - image: 350143100037.dkr.ecr.ap-southeast-1.amazonaws.com/developer-iq-repository:latest
        imagePullPolicy: Always
        name: metrics-app
        ports:
        - containerPort: 3035
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  namespace: developer-iq
  name: metrics-service
spec:
  ports:
    - port: 3035
      targetPort: 3035
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: metrics-app
status:
  loadBalancer: {}
