---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: developer-iq
  name: developer-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: developer-app
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: developer-app
    spec:
      containers:
      - image: 350143100037.dkr.ecr.ap-southeast-1.amazonaws.com/developer-iq-developer-repository:latest
        imagePullPolicy: Always
        name: developer-app
        ports:
        - containerPort: 3034
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  namespace: developer-iq
  name: developer-service
spec:
  ports:
    - port: 3034
      targetPort: 3034
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: developer-app
status:
  loadBalancer: {}
